'use client';
import { useEffect, useState } from 'react';

declare global { interface Window { snap?: { pay: (token: string, callbacks: Record<string, (result: unknown) => void>) => void } } }
type Plan = { id: string; name: string; slug: string; description: string | null; price: number; currency: string; durationDays: number; linkQuota: number; qrQuota: number; apiRateLimit: number; apiKeyQuota: number; features: unknown };
type Billing = { plan: Plan; subscription: { endsAt: string | null } | null; usage: { links: number; qr: number; apiKeys: number }; orders: { id: string; externalId: string; amount: number; status: string; createdAt: string; plan: { name: string } }[] };
type Config = { configured: boolean; clientKey: string; snapJsUrl: string };

export default function BillingPage() {
  const [plans, setPlans] = useState<Plan[]>([]); const [billing, setBilling] = useState<Billing | null>(null); const [config, setConfig] = useState<Config | null>(null); const [message, setMessage] = useState('');
  async function refresh() { const [plansResponse, billingResponse, configResponse] = await Promise.all([fetch('/api/plans'), fetch('/api/billing/status'), fetch('/api/billing/config')]); setPlans(await plansResponse.json()); setBilling(await billingResponse.json()); setConfig(await configResponse.json()); }
  useEffect(() => {
    let active = true;
    Promise.all([fetch('/api/plans'), fetch('/api/billing/status'), fetch('/api/billing/config')]).then(async ([plansResponse, billingResponse, configResponse]) => {
      const [nextPlans, nextBilling, nextConfig] = await Promise.all([plansResponse.json(), billingResponse.json(), configResponse.json()]);
      if (active) { setPlans(nextPlans); setBilling(nextBilling); setConfig(nextConfig); }
    }).catch(() => { if (active) setMessage('Gagal memuat informasi paket.'); });
    return () => { active = false; };
  }, []);
  async function loadSnap(value: Config) { if (window.snap) return; await new Promise<void>((resolve, reject) => { const script = document.createElement('script'); script.src = value.snapJsUrl; script.dataset.clientKey = value.clientKey; script.onload = () => resolve(); script.onerror = () => reject(new Error('Snap.js gagal dimuat')); document.head.appendChild(script); }); }
  async function checkout(plan: Plan) { setMessage('Menyiapkan pembayaran…'); const response = await fetch('/api/billing/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ planId: plan.id }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error); if (data.free) return setMessage(data.message); if (!config?.configured) return setMessage('Midtrans belum dikonfigurasi oleh administrator.'); try { await loadSnap(config); if (!window.snap) throw new Error('Snap tidak tersedia'); window.snap.pay(data.snapToken, { onSuccess: () => { setMessage('Pembayaran berhasil. Menunggu konfirmasi webhook…'); refresh(); }, onPending: () => { setMessage('Pembayaran menunggu penyelesaian.'); refresh(); }, onError: () => { setMessage('Pembayaran gagal.'); refresh(); }, onClose: () => setMessage('Jendela pembayaran ditutup.') }); } catch { if (data.redirectUrl) window.location.assign(data.redirectUrl); else setMessage('Gagal membuka Midtrans Snap.'); } }
  if (!billing) return <main className="mx-auto max-w-7xl p-8 text-slate-400">Memuat paket…</main>;
  return <main className="mx-auto max-w-7xl px-5 py-10"><p className="text-sm font-bold text-cyan-400">PAKET & TAGIHAN</p><h1 className="text-4xl font-black">Paket {billing.plan.name}</h1><p className="mt-2 text-slate-400">{billing.subscription?.endsAt ? `Aktif sampai ${new Date(billing.subscription.endsAt).toLocaleDateString('id-ID')}` : billing.subscription ? 'Paket aktif tanpa batas akhir.' : 'Paket Guest berlaku otomatis.'}</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Usage label="Short links" value={billing.usage.links} limit={billing.plan.linkQuota} /><Usage label="QR tersimpan" value={billing.usage.qr} limit={billing.plan.qrQuota} /><Usage label="API keys" value={billing.usage.apiKeys} limit={billing.plan.apiKeyQuota} /></div>{message && <p className="mt-5 rounded-xl bg-slate-900 p-4 text-cyan-300">{message}</p>}<section className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{plans.map((plan) => { const features = Array.isArray(plan.features) ? plan.features.map(String) : []; return <article key={plan.id} className={`rounded-2xl border p-6 ${plan.slug === billing.plan.slug ? 'border-cyan-400 bg-cyan-950/20' : 'border-slate-800 bg-slate-900'}`}><h2 className="text-2xl font-black">{plan.name}</h2><p className="mt-1 min-h-10 text-sm text-slate-400">{plan.description}</p><div className="mt-4 text-3xl font-black">{plan.price ? `Rp${plan.price.toLocaleString('id-ID')}` : 'Gratis'}<span className="text-xs font-normal text-slate-500"> / {plan.durationDays} hari</span></div><ul className="mt-5 space-y-2 text-sm">{features.map((feature) => <li key={feature}>✓ {feature}</li>)}<li>✓ {plan.linkQuota} short links{plan.slug === 'guest' ? '/hari' : ''}</li><li>✓ {plan.qrQuota} QR tersimpan{plan.slug === 'guest' ? '/hari' : ''}</li><li>✓ API {plan.apiRateLimit} req/menit</li></ul><button disabled={plan.slug === billing.plan.slug} onClick={() => checkout(plan)} className="mt-6 w-full rounded-xl bg-cyan-400 p-3 font-bold text-slate-950 disabled:bg-slate-700 disabled:text-slate-400">{plan.slug === billing.plan.slug ? 'Paket saat ini' : plan.price ? 'Pilih paket' : `Gunakan ${plan.name}`}</button></article>; })}</section><section className="mt-10"><h2 className="text-xl font-bold">Riwayat order</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-500"><tr><th className="p-3">Order</th><th>Paket</th><th>Nominal</th><th>Status</th><th>Tanggal</th></tr></thead><tbody>{billing.orders.map((order) => <tr key={order.id} className="border-t border-slate-800"><td className="p-3 font-mono">{order.externalId}</td><td>{order.plan.name}</td><td>Rp{order.amount.toLocaleString('id-ID')}</td><td>{order.status}</td><td>{new Date(order.createdAt).toLocaleDateString('id-ID')}</td></tr>)}</tbody></table></div></section></main>;
}
function Usage({ label, value, limit }: { label: string; value: number; limit: number }) { return <div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="text-2xl font-bold">{value} / {limit}</div><div className="text-sm text-slate-500">{label}</div><div className="mt-2 h-2 rounded bg-slate-800"><div className="h-2 rounded bg-cyan-400" style={{ width: `${Math.min(100, limit ? value / limit * 100 : 100)}%` }} /></div></div>; }
