'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';

type Key = { id: string; name: string; keyPrefix: string; scopes: string[]; rateLimit: number; lastUsedAt: string | null; revokedAt: string | null; createdAt: string };
const scopes = ['links:read', 'links:write', 'analytics:read', 'qr:write'];

export default function ApiKeysPage() {
  const [keys, setKeys] = useState<Key[]>([]); const [secret, setSecret] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { fetch('/api/api-keys').then((r) => r.json()).then(setKeys); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch('/api/api-keys', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: form.get('name'), scopes: scopes.filter((scope) => form.get(scope) === 'on') }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error); setSecret(data.key); setKeys([data, ...keys]); setMessage(data.warning); event.currentTarget.reset(); }
  async function revoke(id: string) { if (!confirm('Cabut API key ini? Tindakan ini tidak dapat dibatalkan.')) return; const response = await fetch(`/api/api-keys/${id}`, { method: 'DELETE' }); if (response.ok) setKeys(keys.map((key) => key.id === id ? { ...key, revokedAt: new Date().toISOString() } : key)); }
  return <main className="mx-auto max-w-7xl px-5 py-10"><p className="text-sm font-bold text-cyan-400">DEVELOPER</p><h1 className="text-4xl font-black">API Keys</h1><p className="mt-2 text-slate-400">Key disimpan sebagai hash. Nilai lengkap hanya ditampilkan satu kali.</p><form onSubmit={create} className="mt-8 rounded-2xl border border-slate-800 bg-slate-900 p-6"><input name="name" required minLength={2} placeholder="Nama key (mis. Integrasi CRM)" className="w-full rounded-xl bg-slate-950 p-3" /><div className="mt-4 flex flex-wrap gap-4">{scopes.map((scope) => <label key={scope} className="text-sm"><input type="checkbox" name={scope} /> {scope}</label>)}</div><button className="mt-5 rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">Buat API key</button></form>{secret && <section className="mt-5 rounded-2xl border border-amber-600 bg-amber-950/30 p-5"><b className="text-amber-300">Salin sekarang</b><code className="mt-3 block break-all rounded-xl bg-slate-950 p-4">{secret}</code><button onClick={() => navigator.clipboard.writeText(secret)} className="mt-3 text-sm text-cyan-400">Salin ke clipboard</button></section>}{message && <p className="mt-3 text-sm text-amber-300">{message}</p>}<section className="mt-8 space-y-3">{keys.map((key) => <article key={key.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-800 bg-slate-900 p-5"><div><b>{key.name}</b><code className="ml-3 text-cyan-400">{key.keyPrefix}…</code><p className="mt-1 text-xs text-slate-500">{key.scopes.join(', ')} · {key.rateLimit}/menit · terakhir: {key.lastUsedAt ? new Date(key.lastUsedAt).toLocaleString('id-ID') : 'belum digunakan'}</p></div>{key.revokedAt ? <span className="text-sm text-red-400">Dicabut</span> : <button onClick={() => revoke(key.id)} className="rounded-lg border border-red-900 px-3 py-2 text-sm text-red-400">Cabut</button>}</article>)}</section><Link href="/docs" className="mt-8 inline-block text-cyan-400">Buka dokumentasi REST API →</Link></main>;
}
